Test: Add smoke test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,6 +15,11 @@ jobs:
         run: git lfs checkout
       - name: Run build
         run: ./gradlew build
+      - name: Upload artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: jakharidi-jar
+          path: build/libs/jakharidi-0.0.1-SNAPSHOT.jar
   test:
     runs-on: ubuntu-20.04
     steps:
@@ -25,3 +30,25 @@ jobs:
         run: git lfs checkout
       - name: Run build
         run: ./gradlew test
+  smoke-test:
+    runs-on: ubuntu-20.04
+    needs: build
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: jakharidi-jar
+      - run: java -version
+      - name: Start the application
+        run: |
+          java -jar jakharidi-0.0.1-SNAPSHOT.jar &
+          exit_code=$!
+          if [ $exit_code -ne 0]; then
+          echo "Failed to start application"
+          echo "Exit code: $exit_code"
+          exit 1
+          fi
+          echo "Waiting for the app to start..."
+          sleep 2
+      - name: Healthcheck
+        run: curl --fail localhost:8080/actuator/health
